version: '3.7'

services:
  web:
    container_name: bookbnb-appserver_web

    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./:/usr/src/app

    ports:
      - 3000:8080

    depends_on:
      - db # first execute database

    environment:
      - TESTING=0
      - ENVIRONMENT
      - DATABASE_URL=postgres://user:password@db/appserver_db_dev
      - FIREBASE-CLIENT-CERT-URL
      - FIREBASE-CLIENT-EMAIL
      - FIREBASE-CLIENT-ID
      - FIREBASE-PRIVATE-KEY
      - FIREBASE-PRIVATE-KEY-ID
      - FIREBASE-PROJECT-ID
      - FIREBASE-STORAGE-BUCKET

  db:
    container_name: bookbnb-appserver_db

    image: postgres:12.1-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appserver_db_dev

volumes:
  postgres_data:
